### ISSUE TITLE
Update Readme to Reflect Deprecation of Password-based HTTPS Auth

### ISSUE THREAD

**Issue by twalker1123-ActOn** [intel/credit-card-fraud-detection#1]
Step 3 of **Getting Started** should be updated to account for deprecation of password-based auth to clone from Github.

It currently reads:
```
git clone https://github.com/intel/credit-card-fraud-detection # to be replaced by external git link
cd credit-card-fraud-detection
git submodule update --init --recursive
```

There should be a blurb somewhere above noting how to create a Personal Access Token. The above would then be amended to:
```
git clone https://<your PAT here>@github.com/intel/credit-card-fraud-detection # to be replaced by external git link
cd credit-card-fraud-detection
```
Then open `.git/config` and amend the submodule repositories:
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://<your PAT already here>@github.com/intel/credit-card-fraud-detection
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
        remote = origin
        merge = refs/heads/main
[submodule "classical-ml"]
        url = https://<your PAT here>@github.com/intel/recommender-system-with-distributed-classical-ml
[submodule "gnn-analytics"]
        url = https://<your PAT here>@github.com/intel/graph-neural-networks-and-analytics
~                                                                                                                      
```

Then finally:
```
git submodule update --init --recursive
```

**Comment by adkakne** [comment]
Hi @twalker1123-ActOn, thank you for submitting this issue. To accommodate needs of diverse user groups, we provide 5 ways to run our end-to-end pipeline. But, this means keeping the README short and sweet is a challenge. Thus, we assume that - the user is familiar with GitHub, conda and common bash commands. Nevertheless, your issue will be helpful if anyone runs into similar problem. Thank you!
